### ISSUE TITLE
About Many Bug Issue

### ISSUE THREAD

**Issue by tpsy12021** [Nicc0/Sky-Wars#11]
One people in game will make game broken
[21:29:47] [Server thread/WARN]: java.lang.NoSuchFieldException: j
[21:29:47] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[21:29:47] [Server thread/WARN]: 	at org.skywars.s.a$b.setField(API_PacketsScoreboard.java:589)
[21:29:47] [Server thread/WARN]: 	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:563)
[21:29:47] [Server thread/WARN]: 	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:509)
[21:29:47] [Server thread/WARN]: 	at org.skywars.s.a$b.s(API_PacketsScoreboard.java:475)
[21:29:47] [Server thread/WARN]: 	at org.skywars.g.b.ag(Game.java:1592)
[21:29:47] [Server thread/WARN]: 	at org.skywars.g.b$1.run(Game.java:434)
[21:29:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[21:29:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[21:29:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[21:29:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:29:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:29:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:29:47] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:29:47] [Server thread/WARN]: [LeakSkyWars] Task #27 for LeakSkyWars v2.0.03 generated an exception
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Collection
	at org.skywars.s.a$b.z(API_PacketsScoreboard.java:528) ~[?:?]
	at org.skywars.s.a$b.y(API_PacketsScoreboard.java:517) ~[?:?]
	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:566) ~[?:?]
	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:509) ~[?:?]
	at org.skywars.s.a$b.s(API_PacketsScoreboard.java:475) ~[?:?]
	at org.skywars.g.b.ag(Game.java:1592) ~[?:?]
	at org.skywars.g.b$1.run(Game.java:434) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[21:29:58] [Server thread/WARN]: [LeakSkyWars] Task #27 for LeakSkyWars v2.0.03 generated an exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_161]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_161]
	at org.skywars.g.b.ac(Game.java:1379) ~[?:?]
	at org.skywars.g.b.e(Game.java:56) ~[?:?]
	at org.skywars.g.b$1.run(Game.java:498) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[21:30:08]

and other Error
[21:30:58] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to LeakSkyWars v2.0.03
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at org.skywars.w.f.b(Utils_Check.java:50) ~[?:?]
	at org.skywars.k.k.a(EventMove.java:39) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 15 more

Cage cannot break 
sw lobby and sw setroom which is different
start game will go Game End and time to 60:00
game start cage not open 
and many bug

**Comment by tpsy12021** [comment]
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:348) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:871) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:314) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Collection
	at org.skywars.s.a$b.B(API_PacketsScoreboard.java:547) ~[?:?]
	at org.skywars.s.a$b.A(API_PacketsScoreboard.java:536) ~[?:?]
	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:570) ~[?:?]
	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:509) ~[?:?]
	at org.skywars.s.a$b.a(API_PacketsScoreboard.java:497) ~[?:?]
	at org.skywars.g.b.i(Game.java:1570) ~[?:?]
	at org.skywars.g.b.e(Game.java:1182) ~[?:?]
	at org.skywars.g.b.b(Game.java:199) ~[?:?]
	at org.skywars.k.i.a(EventLeave.java:29) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 12 more

and this
