### ISSUE TITLE
[ERROR] when making NPC

### ISSUE THREAD

**Issue by CriZpyPvP** [Nicc0/Sky-Wars#13]
Error:
[18:11:47 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.Entity.setNoGravity(boolean)
[18:11:47 WARN]:        at java.lang.Class.getDeclaredMethod(Class.java:2130)
[18:11:47 WARN]:        at org.skywars.m.f.create(NPC_Holograms.java:168)
[18:11:47 WARN]:        at org.skywars.m.f.<init>(NPC_Holograms.java:37)
[18:11:47 WARN]:        at org.skywars.m.m.a(NPC_Lobby.java:123)
[18:11:47 WARN]:        at org.skywars.d.a.p.d(NPCCommand.java:134)
[18:11:47 WARN]:        at org.skywars.d.a.p.a(NPCCommand.java:54)
[18:11:47 WARN]:        at org.skywars.d.b.onCommand(CommandArena.java:71)
[18:11:47 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:11:47 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[18:11:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:11:47 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:11:47 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[18:11:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[18:11:47 WARN]:        at java.lang.Thread.run(Thread.java:748)
--------------------------------------------------------------------------------------
NPC created successfully but without Holograms.
i installed holographic display then uninstall it. i tried both with hd and without hd.

Spigot version: Paperclip 1.8.8

**Comment by CriZpyPvP** [comment]
bump. im still waiting bro.

**Comment by Nicc0** [comment]
Fixed
