### ISSUE TITLE
Doesnt even work

### ISSUE THREAD

**Issue by crazymankills** [Nicc0/Sky-Wars#7]
When I try to create a map it just says /skywars create < name > < type > < flag > and youre wiki doesnt specify to put where it says type and flag

**Comment by crazymankills** [comment]
08.04 12:24:29 [Server] INFO [LeakSkyWars] Enabling LeakSkyWars v2.0.02
08.04 12:24:29 [Server] INFO [LeakSkyWars] Disabling LeakSkyWars v2.0.02
08.04 12:24:29 [Server] ERROR Error occurred while enabling LeakSkyWars v2.0.02 (Is it up to date?)
08.04 12:24:29 [Server] INFO java.lang.NullPointerException: null
08.04 12:24:29 [Server] INFO at org.skywars.api.Start.sendMessage(Start.java:234) ~[?:?]
08.04 12:24:29 [Server] INFO at org.skywars.api.Start.onEnable(Start.java:118) ~[?:?]
08.04 12:24:29 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~

**Comment by crazymankills** [comment]
Like the plugin isnt even working.
